### PR TITLE
fix linux builds on unsupported arch tracing helpers

### LINKED ISSUE #684: [Bug]: Support riscv64, ppc64el, s390x etc -- missing `getSyscallArgs`
Building in-toto/go-witness 0.9.2 in Debian on fails like this for non-amd64/arm64/i386 platforms:

```
1269s github.com/in-toto/go-witness/attestation/commandrun
1272s # github.com/in-toto/go-witness/attestation/commandrun
1272s src/github.com/in-toto/go-witness/attestation/commandrun/tracing_linux.go:167:14: undefined: getSyscallArgs
1272s src/github.com/in-toto/go-witness/attestation/commandrun/tracing_linux.go:168:15: undefined: getSyscallId
1272s src/github.com/in-toto/go-witness/attestation/commandrun/tracing_linux.go:280:9: undefined: getNativeUint
```

The cause seems obvious looking at:

https://github.com/in-toto/go-witness/tree/main/attestation/commandrun

It has implementations for amd64, arm, arm64, and i386 -- but not any other platform.  And the `tracing_unsupported.go` file does not implement these APIs and is for non-linux platforms only.

Could you implement stubs that works everywhere?  Or at least on all linux.

Thanks,
Simon

### PR DESCRIPTION
**Pull request by Jaydeep869**
## What this PR does / why we need it

Fixes Linux build failures on architectures that do not have architecture specific ptrace syscall helper implementations (for example `riscv64`, `s390x`, `ppc64le`) in `attestation/commandrun`.

Changes made:
- Add a Linux fallback helper file for unsupported arches:
  - `attestation/commandrun/tracing_linux_unsupported_arch.go`
  - provides fallback `getSyscallId` / `getSyscallArgs` so package compiles on all Linux arches.
- Remove architecture specific `getNativeUint` dependency by switching to `Iovec.SetLen()` in:
  - `attestation/commandrun/tracing_linux.go`

This keeps current behavior for supported arch-specific files (`amd64`, `arm64`, `arm`, `386`) while preventing compile time breakage on other Linux targets.

## Which issue(s) this PR fixes (optional)

Fixes #684

## Acceptance Criteria Met

- [ ] Docs changes if needed
- [x] Testing changes if needed
- [ ] All workflow checks passing (automatically enforced)
- [ ] All review conversations resolved (automatically enforced)
- [x] [DCO Sign-off](https://github.com/apps/dco)

**Special notes for your reviewer**:
Validated with:
- `go test ./attestation/commandrun`
- `GOOS=linux GOARCH=riscv64 go test -c ./attestation/commandrun`
- `GOOS=linux GOARCH=s390x go test -c ./attestation/commandrun`
- `GOOS=linux GOARCH=ppc64le go test -c ./attestation/commandrun`

Fallback helpers intentionally avoid arch specific register decoding for now; this PR focuses on build portability and unblocking downstream packaging.

### CODE REVIEW

File: attestation/commandrun/tracing_linux.go [hunk 1]
```diff
@@ -441,8 +441,8 @@ func (ctx *ptraceContext) readSyscallReg(pid int, addr uintptr, n int) (string,
 	data := make([]byte, n)
 	localIov := unix.Iovec{
 		Base: &data[0],
-		Len:  getNativeUint(n),
 	}
+	localIov.SetLen(n)
```
Comment (jkjell) [inline attestation/commandrun/tracing_linux.go:445]: This removes the need for the `getNativeUint` function in the platform specific tracing files (hence the golangci_lint failure). Could you remove this functions from:
- attestation/commandrun/tracing_linux_386.go
- attestation/commandrun/tracing_linux_amd64.go
- attestation/commandrun/tracing_linux_arm.go
- attestation/commandrun/tracing_linux_arm64.go

Thanks!

File: commandrun.test
Comment (jkjell) [inline commandrun.test:1]: Can you remove this file?

**Review by jkjell — APPROVED** [review]
